version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: bolson
      MYSQL_DATABASE: pablo
      MYSQL_USER: frodo
      MYSQL_PASSWORD: bolson
    volumes:
      - ./data:/var/lib/mysql

  web:
    build:
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - mysql
